name: Delphi Build

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ self-hosted, windows ]

    env:
      BDS: 'C:\Program Files (x86)\Embarcadero\Studio\23.0'
      DEVEXPRESS_RS29: 'C:\Program Files (x86)\DevExpress\VCL\Library\RS29\Win64'
      MADEXCEPT_RS29: 'C:\Program Files (x86)\madCollection\madExcept\BDS23\win64'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build project
      shell: cmd
      run: |
        call "%BDS%\bin\rsvars.bat"
        dcc64.exe "%GITHUB_WORKSPACE%\AlgorithmShowcase.dpr" ^
          -B -Q ^
          -NS"System;Xml;Data;Datasnap;Web;Soap;Vcl;Winapi" ^
          -U"%DEVEXPRESS_RS29%;%MADEXCEPT_RS29%;%BDS%\lib\win64\release" ^
          -O"%BDS%\lib\win64\release" ^
          -L"%BDS%\lib\win64\release"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: algorithm-showcase-exe
        path: AlgorithmShowcase.exe
